# Generated by Django 6.0.4 on 2026-04-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('purpose', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('IN', 'Cash In'), ('OUT', 'Payment/Expense')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
