# Generated by Django 6.0.4 on 2026-04-29 07:38

import calculator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_transaction_remarks_alter_purpose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name=models.DateField(validators=[calculator.models.Transaction.validate_year])),
        ),
    ]
